### ISSUE TITLE
Remove psi from the exercises.

### ISSUE THREAD

**Issue by hemanth** [bevacqua/perfschool#1]
As they are bringing it [down](https://developers.google.com/speed/pagespeed/service/Deprecation)!

**Comment by bevacqua** [comment]
No. They're not.

**Comment by hemanth** [comment]
Oh! Ok.

It read:

> 5th May announced that PageSpeed Service will be turned down.

**Comment by bevacqua** [comment]
Yes. That's a CloudFlare-like service. Not PageSpeed Insights nor any of their open-source products around it. See: https://news.ycombinator.com/item?id=9500195

**Comment by hemanth** [comment]
That was confusing! I was wondering what was the reason behind it.

Thanks.

> PageSpeed Service: Google-hosted proxy version of the PageSpeed Modules.
