### ISSUE TITLE
ENOENT on windows

### ISSUE THREAD

**Issue by theHazzard** [bevacqua/perfschool#2]
In perfschool windows does not create the folder perfschool-playground.
It can be solved by manually creating it, but I thought it would be nice to open an issue. 
Nice work on this!

**Comment by bevacqua** [comment]
Weird. Shouldn't this line do that? https://github.com/bevacqua/perfschool/blob/master/lib/init.js#L35

**Comment by theHazzard** [comment]
I thought the same, but looks like windows does not like it D=

**Comment by theHazzard** [comment]
![error](https://cloud.githubusercontent.com/assets/1127332/7686743/80b30a7e-fd6e-11e4-92e5-37b25d376030.png)
![error2](https://cloud.githubusercontent.com/assets/1127332/7686785/bc606cc4-fd6e-11e4-86ec-844338b756e5.png)

**Comment by theHazzard** [comment]
it's weird, it doesn't copy anything either... I mean, if it populates the folder with some bootstrap files
![error3](https://cloud.githubusercontent.com/assets/1127332/7687545/6a19f3ee-fd74-11e4-89b1-b3995291e372.png)

**Comment by bevacqua** [comment]
Fixed in `1.0.1`
