### ISSUE TITLE
Failed at the contextify@0.1.14 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by GomesNayagam** [bevacqua/perfschool#5]
## getting the following error when i try to install at windows box. 

54295 error node v0.12.0
54296 error npm  v2.5.1
54297 error code ELIFECYCLE
54298 error contextify@0.1.14 install: `node-gyp rebuild`
54298 error Exit status 1
54299 error Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
54299 error This is most likely a problem with the contextify package,
54299 error not with npm itself.
54299 error Tell the author that this fails on your system:
54299 error     node-gyp rebuild
54299 error You can get their info via:
54299 error     npm owner ls contextify
54299 error There is likely additional logging output above.

**Comment by bevacqua** [comment]
> 54295 error node v0.12.0

Fix yer `node-gyp`.

```
npm install node-gyp-install && ./node_modules/node-gyp-install/bin.js
```

**Comment by GomesNayagam** [comment]
still problem ,

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform
Toolset = 'v100') cannot be found. To build using the v100 build tools, either
click the Project menu or right-click the solution, and then select "Update VC+
- Projects...". Install Visual Studio 2010 to build using the Visual Studio 201
  0 build tools. [C:\Users\goma1940\node_modules\perfschool\node_modules\jsdom\no
  de_modules\contextify\build\contextify.vcxproj]
  gyp ERR! build error
  gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
  ` failed with exit code: 1
  gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
  dules\npm\node_modules\node-gyp\lib\build.js:267:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
  :12)
  gyp ERR! System Windows_NT 6.1.7601
  gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
  e_modules\node-gyp\bin\node-gyp.js" "rebuild"
  gyp ERR! cwd C:\Users\goma1940\node_modules\perfschool\node_modules\jsdom\node_m
  odules\contextify
  gyp ERR! node -v v0.12.0
  gyp ERR! node-gyp -v v1.0.2
  gyp ERR! not ok

**Comment by bevacqua** [comment]
Please refer to the [`node-gyp`](https://github.com/TooTallNate/node-gyp) repo for issues related to it.

**Comment by GomesNayagam** [comment]
Appreciate that, unfortunately it works only this way for windows  : npm install -g perfschool --msvs_version=2012

**Comment by qqxufo** [comment]
solved?I'm getting the same error when i try to install it.

**Comment by GomesNayagam** [comment]
as the author mentioned it is node-gyp issue, check your visual studio version and use npm install -g perfschool --msvs_version=xxxx

**Comment by qqxufo** [comment]
I use vs 2012.but --msvs_version=2012 useless.I getting the following error.

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
 ERR! command "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\A
ppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.
js" "rebuild"
gyp ERR! cwd E:\Program Files\nodejs\node_modules\perfschool\node_modules\jsdom\
node_modules\contextify
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

```
PhantomJS not found on PATH
```

```
npm ERR! node v5.5.0
npm ERR! npm  v2.14.17
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
```

**Comment by IgorMilosavljevic** [comment]
Strange but this is what solved for me http://stackoverflow.com/a/33716573/3116607
I believe this is a similar solution to the one OP mentioned. Basically by starting a C++ project in Visual Studio VS installs a couple of libraries on your machine. And that solved the issue.
