### ISSUE TITLE
Alternative solution to ENFORCING A PERFORMANCE BUDGET

### ISSUE THREAD

**Issue by MylesBorins** [bevacqua/perfschool#6]
Going through step four I managed to get optimized images directly from imgur by including a single character "m" at the end of the image id's.

Info here --> https://api.imgur.com/models/image

Similar to looking at the code and seeing bits you don't need to use, I think it is important to examine the api's you are using and find out what you can get for free.

If you are open to this being included I can send a PR with updated copy.

**Comment by bevacqua** [comment]
Yes! PR me!
